update build config

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-# Copyright 2010-2022 by Sebastian Thomschke and contributors.
+# Copyright 2010-2023 by Sebastian Thomschke and contributors.
 # SPDX-License-Identifier: EPL-2.0
 #
 # Author: Sebastian Thomschke, https://sebthom.de/
@@ -28,6 +28,10 @@ on:
 # https://docs.github.com/en/actions/using-jobs/using-concurrency
 concurrency: ci-${{ github.ref }}
 
+defaults:
+  run:
+    shell: bash
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -45,14 +49,26 @@ jobs:
         - java: 19
           may_create_release: false
           experimental: false
+
     steps:
+    - name: "ACT: Install ping"
+      if: runner.os == 'Linux' && env.ACT # https://github.com/nektos/act#skipping-steps
+      run: |
+        if ! hash ping 2>/dev/null; then
+          apt-get update
+          apt-get -y install iputils-ping
+        fi
+
+    - name: Show environment variables
+      run: env | sort
+
     - name: Git Checkout
       uses: actions/checkout@v3 #https://github.com/actions/checkout
 
     - name: Set up JDK ${{ matrix.java }}
       uses: actions/setup-java@v3 #https://github.com/actions/setup-java
       with:
-        distribution: 'zulu'
+        distribution: temurin
         java-version: ${{ matrix.java }}
 
     # reusing CDS archives of the same JVM randomly fails in GitHub Actions with
@@ -68,26 +84,20 @@ jobs:
     #      ~/.xshare/${{ steps.java-version-checksum.outputs.md5sum }}
     #    key: ${{ runner.os }}-xshare-${{ steps.java-version-checksum.outputs.md5sum }}
 
-    - name: "Cache: Local Maven Repository"
-      uses: actions/cache@v3
-      with:
-        path: |
-          ~/.m2/repository
-          !~/.m2/repository/net/sf/jstuff
-        key: ${{ runner.os }}-mvnrepo-${{ hashFiles('**/pom.xml') }}
-        restore-keys: |
-          ${{ runner.os }}-mvnrepo-
-
-    - name: "Cache: Maven Binaries"
-      uses: actions/cache@v3
+    - name: "Cache: Restore"
+      id: cache-restore
+      if: ${{ !env.ACT }} # https://github.com/nektos/act#skipping-steps
+      uses: actions/cache/restore@v3
       with:
         path: |
           ~/.m2/bin
-        key: ${{ runner.os }}-mvnbin-${{ hashFiles('.ci/build.sh') }}
+          ~/.m2/repository
+          !~/.m2/repository/net/sf/jstuff
+        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
 
     - name: Test with Maven
       id: maven-test
-      if: ${{ !matrix.may_create_release }}
+      if: ${{ !matrix.may_create_release || env.ACT }}
       env:
         GITHUB_USER: ${{ github.actor }}
         GITHUB_API_KEY: ${{ github.token }}
@@ -98,13 +108,13 @@ jobs:
 
     - name: Build with Maven
       id: maven-build
-      if: matrix.may_create_release
+      if: ${{ matrix.may_create_release && !env.ACT }}
       env:
         DEPLOY_SNAPSHOTS_TO_GITHUB_BRANCH: true
         GITHUB_USER: ${{ github.actor }}
         GITHUB_API_KEY: ${{ secrets.GH_API_TOKEN }}
         JAVA_VERSION: ${{ matrix.java }}
-        MAY_CREATE_RELEASE: ${{ matrix.may_create_release }}
+        MAY_CREATE_RELEASE: true
         SIGN_KEY: ${{ secrets.GPG_SIGN_KEY }}
         SIGN_KEY_PASS: ${{ secrets.GPG_SIGN_KEY_PWD }}
         SONATYPE_OSSRH_USER: ${{ secrets.SONATYPE_OSSRH_USER }}
@@ -123,7 +133,7 @@ jobs:
 
     - name: Publish test coverage to codeclimate.com
       uses: paambaati/codeclimate-action@v3.2.0 # https://github.com/paambaati/codeclimate-action
-      if: matrix.may_create_release && steps.maven-build.outputs.has_jacoco_results
+      if: ${{ matrix.may_create_release && steps.maven-build.outputs.has_jacoco_results && !env.ACT }}
       env:
         CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
         JACOCO_SOURCE_PATH: "${{ github.workspace }}/jstuff-core/src/main/java ${{ github.workspace }}/jstuff-integration/src/main/java ${{ github.workspace }}/jstuff-xml/src/main/java"
@@ -135,3 +145,42 @@ jobs:
           ${{ github.workspace }}/jstuff-integration/target/site/jacoco-it/jacoco.xml:jacoco
           ${{ github.workspace }}/jstuff-xml/target/site/jacoco/jacoco.xml:jacoco
           ${{ github.workspace }}/jstuff-xml/target/site/jacoco-it/jacoco.xml:jacoco
+
+
+    ##################################################
+    # Cache Update
+    # See https://github.com/actions/cache/issues/342
+    ##################################################
+    - name: "Cache: Delete Previous"
+      if: ${{ steps.cache-restore.outputs.cache-hit && !env.ACT }}
+      env:
+        GH_TOKEN: ${{ github.token }}
+      run: |
+        gh extension install actions/gh-actions-cache
+        gh actions-cache delete ${{ steps.cache-restore.outputs.cache-primary-key }} --confirm
+
+    - name: "Cache: Update"
+      uses: actions/cache/save@v3
+      if: ${{ always() && !env.ACT }} # save cache even fails
+      with:
+        path: |
+          ~/.m2/bin
+          ~/.m2/repository
+          !~/.m2/repository/net/sf/jstuff
+        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
+
+
+  ###########################################################
+  cleanup:
+  ###########################################################
+    runs-on: ubuntu-latest
+    needs: 
+      - build
+
+    steps:
+    - name: "Delete intermediate build artifacts"
+      if: ${{ !env.ACT }} # https://github.com/nektos/act#skipping-steps
+      uses: geekyeggo/delete-artifact@v2 # https://github.com/GeekyEggo/delete-artifact/
+      with:
+        name: "*"
+        failOnError: false
